excluded: # paths to ignore during linting.
  - Example/Pods
  - Example/SuperAwesomeExampleTests/Common/Components/VastParserTests.swift
  - Example/SuperAwesomeExampleTests/Common/Components/HtmlFormatterTests.swift
identifier_name:
  min_length: 1
  allowed_symbols: ["_"]
type_name:
  min_length: 1
line_length:
  warning: 170
disabled_rules:
  - function_parameter_count
  - function_body_length
  - cyclomatic_complexity
  - type_body_length
