# .circleci/config.yml
version: 2.1

orbs:
  swiftlint: ngs/swiftlint@0.0.1

jobs:
  build-and-test:
    macos:
      xcode: 12.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      
      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: cd Example && bundle exec pod install
          
      - run:
          name: swiftLint
          command: swiftlint
          
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
          
  setupFastLane:
    macos:
      xcode: 12.4.0
    steps:
      - checkout
      - run:
          name: Select Ruby Version
          command:  echo "ruby-2.4" > .ruby-version
      - restore_cache:
          keys:
          - m2-gems-{{ checksum "Gemfile.lock" }}
          - m2-gems-
      - run:
          name: Install Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - save_cache:
          key: m2-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

workflows:
  build-test:
    jobs:
      - setupFastLane
      - build-and-test
