# .circleci/config.yml
version: 2.1
references:

  ios_config: &ios_config
    macos:
      xcode: 14.1.0
    resource_class: macos.x86.medium.gen2
    environment:
      FL_OUTPUT_DIR: output
      LC_ALL: en_GB.UTF-8
      LANG: en_GB.UTF-8

  configure_google_services: &configure_google_services
    run:
      name: Configure Google Services
      command: |
        echo "Google Services"
        echo 'export SA_IOS_SDKS_GOOGLE_SERVICES_PLIST_ENC="$SA_IOS_SDKS_GOOGLE_SERVICES_PLIST_ENC"' >> $BASH_ENV
        echo $SA_IOS_SDKS_GOOGLE_SERVICES_PLIST_ENC | base64 --decode > Example/SuperAwesome/${SA_IOS_SDKS_GOOGLE_SERVICES_PLIST_NAME}.plist

jobs:
  build-and-test:
    <<: *ios_config
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - *configure_google_services
      - run: bundle install
      
      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: cd Example && bundle exec pod install
          
      - run:
          name: Fastlane
          command: |
            /usr/bin/java ./Example/SuperAwesomeExampleUITests/MockServer/WireMock.jar &
            bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
          
  swiftlint:
    docker:
      - image: bytesguy/swiftlint:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - *configure_google_services
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
          
  setup-FastLane:
    <<: *ios_config
    steps:
      - checkout
      - *configure_google_services
      - run:
          name: Select Ruby Version
          command:  echo "ruby-2.4" > .ruby-version
      - restore_cache:
          keys:
          - m2-gems-{{ checksum "Gemfile.lock" }}
          - m2-gems-
      - run:
          name: Install Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - save_cache:
          key: m2-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

workflows:
  build-test:
    jobs:
      - swiftlint:
          context: MOBILE_IOS_SDKS
      - setup-FastLane:
          context: MOBILE_IOS_SDKS
      - build-and-test:
          context: MOBILE_IOS_SDKS

